### ISSUE TITLE
Issue with a postal code not found

### ISSUE THREAD

**Issue by parad0x96** [verhovsky/postalcodes-ca#2]
I tried this library with this postal code "H1H 1H1" which is a valid postal code and got an exception .
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python39\lib\site-packages\postalcodes_ca\__init__.py", line 273, in __getitem__
    raise KeyError(code)
KeyError: 'H1H 1H1'
```

**Comment by verhovsky** [comment]
Looking up "H1H 1H1" on https://www.canadapost-postescanada.ca/info/mc/personal/postalcode/fpc.jsf produces no results. When I look it up on google maps, it comes up with the address

> 1234 testing avenue, Montreal, Quebec H1H 1H1

Looks like it's not a real postal code to me.
